### ISSUE TITLE
Suggestion regarding ux

### ISSUE THREAD

**Issue by octobersecond** [rishipurwar1/The-Web-Developer-Bootcamp-2020#1]
Hey.. That's a good initiative but I think creating multiple branches for each section just isn't right. Maybe you are already aware of the use of branches, hence I am not going to dwell on it. The easy way I think is to create a **resources** directory and inside it creating _section1.md_ and so on and linking them to Readme.md in the root directory by [section1].(resources/section1.md). That was just a suggestion and you are free to ignore it!! Btw nice way to make github time productive..

**Comment by rishipurwar1** [comment]
Thanks for your suggestion.
I already added a video guide to show users how to navigate through different solutions using the branches dropdown menu If the users don't know how to work with branches.

**Comment by octobersecond** [comment]
Sure !!
